### ISSUE TITLE
NoMethodError: undefined method `<' for nil:NilClass

### ISSUE THREAD

**Issue by jgorset** [benaubin/wit_bot#2]
Cool gem, @penne12! I like this abstraction a lot more than WitAI's official client, which really doesn't feel like Ruby at all. I got this error when I tried it, though – is it due to Wit's new story API, or did I just miss something?

Here's my code (it's built on [hyperoslo/facebook-messenger](https://github.com/hyperoslo/facebook-messenger), but you get the idea):

``` ruby
require 'facebook/messenger'
require 'wit_bot'

include Facebook::Messenger

WitBot.configure do |config|
  config.token = ENV['WIT_ACCESS_TOKEN']
end

Facebook::Messenger.configure do |config|
  config.access_token = ENV['FACEBOOK_ACCESS_TOKEN']
  config.verify_token = ENV['FACEBOOK_VERIFY_TOKEN']
end

Bot.on :message do |message|
  thread = WitBot::MessageThread.new(message.sender['id'])
  message = WitBot::Message.new(thread, message.text)

  message.send
end
```

```
NoMethodError: undefined method `<' for nil:NilClass
        /Users/jgorset/.gem/ruby/2.3.0/gems/wit_bot-0.5.7/lib/wit_bot/models/outcome.rb:19:in `low_confidence?'
        /Users/jgorset/.gem/ruby/2.3.0/gems/wit_bot-0.5.7/lib/wit_bot/models/outcome.rb:15:in `initialize'
        /Users/jgorset/.gem/ruby/2.3.0/gems/wit_bot-0.5.7/lib/wit_bot/models/message.rb:72:in `new'
        /Users/jgorset/.gem/ruby/2.3.0/gems/wit_bot-0.5.7/lib/wit_bot/models/message.rb:72:in `block in parse_outcomes'
        /Users/jgorset/.gem/ruby/2.3.0/gems/wit_bot-0.5.7/lib/wit_bot/models/message.rb:72:in `each'
        /Users/jgorset/.gem/ruby/2.3.0/gems/wit_bot-0.5.7/lib/wit_bot/models/message.rb:72:in `each_with_index'
        /Users/jgorset/.gem/ruby/2.3.0/gems/wit_bot-0.5.7/lib/wit_bot/models/message.rb:72:in `each'
        /Users/jgorset/.gem/ruby/2.3.0/gems/wit_bot-0.5.7/lib/wit_bot/models/message.rb:72:in `map'
        /Users/jgorset/.gem/ruby/2.3.0/gems/wit_bot-0.5.7/lib/wit_bot/models/message.rb:72:in `parse_outcomes'
        /Users/jgorset/.gem/ruby/2.3.0/gems/wit_bot-0.5.7/lib/wit_bot/models/message.rb:76:in `parse_outcomes!'
        /Users/jgorset/.gem/ruby/2.3.0/gems/wit_bot-0.5.7/lib/wit_bot/models/message.rb:66:in `send'
        /Users/jgorset/Code/ruby/witai/bot.rb:19:in `block in <top (required)>'
        /Users/jgorset/.gem/ruby/2.3.0/gems/facebook-messenger-0.4.2/lib/facebook/messenger/bot.rb:63:in `trigger'
        /Users/jgorset/.gem/ruby/2.3.0/gems/facebook-messenger-0.4.2/lib/facebook/messenger/bot.rb:51:in `receive'
        /Users/jgorset/.gem/ruby/2.3.0/gems/facebook-messenger-0.4.2/lib/facebook/messenger/server.rb:47:in `block (2 levels) in receive'
        /Users/jgorset/.gem/ruby/2.3.0/gems/facebook-messenger-0.4.2/lib/facebook/messenger/server.rb:46:in `each'
        /Users/jgorset/.gem/ruby/2.3.0/gems/facebook-messenger-0.4.2/lib/facebook/messenger/server.rb:46:in `block in receive'
        /Users/jgorset/.gem/ruby/2.3.0/gems/facebook-messenger-0.4.2/lib/facebook/messenger/server.rb:43:in `each'
        /Users/jgorset/.gem/ruby/2.3.0/gems/facebook-messenger-0.4.2/lib/facebook/messenger/server.rb:43:in `receive'
        /Users/jgorset/.gem/ruby/2.3.0/gems/facebook-messenger-0.4.2/lib/facebook/messenger/server.rb:19:in `call'
        /Users/jgorset/.gem/ruby/2.3.0/gems/facebook-messenger-0.4.2/lib/facebook/messenger/server.rb:10:in `call'
        /Users/jgorset/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
        /Users/jgorset/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
        /Users/jgorset/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
        /Users/jgorset/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
        /Users/jgorset/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
        /Users/jgorset/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
        /Users/jgorset/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
        /Users/jgorset/.gem/ruby/2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
        /Users/jgorset/.rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
        /Users/jgorset/.rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
        /Users/jgorset/.rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'
```

**Comment by benaubin** [comment]
Is your app an older one (that hasn't been migrated to stories)? If so, my client should still work. Otherwise, it probably won't. Sorry! 

I definitely want to fix my client, but I haven't gotten a chance - I really need to focus on a personal project (presenting at my local Maker Faire this weekend!), anyways, I plan on getting around to this next week. 

I've tried to patch it to work with old wit.ai projects, but it should be expected not to work if you are using a newer app.

Sorry about that.

If you'd like to try to get the new story api working, I'd love to see a PR - otherwise, I can try to get it done next week.

**Comment by jgorset** [comment]
No worries! I thought as much when I saw #1, but wanted to make sure. We're toying with bots at @hyperoslo these days, so we might just send some pull requests your way!

**Comment by jgorset** [comment]
Some immediate ideas for an API (again with [hyperoslo/facebook-messenger](https://github.com/hyperoslo/facebook-messenger) for demonstration purposes):

``` ruby
WitBot.on :say do |thread, message|
  Bot.deliver(
    recipient: {
      id: session.id
    },
    message: {
      text: message
    }
  )
end

WitBot.on :greet do |thread|
  thread.context.greeting = ['Hello', 'Hi', 'Hiya'].sample
end

Bot.on :message do |message|
  thread = WitBot::MessageThread.new(message.sender['id'])

  WitBot.run message.text, on: thread
end
```

For comparison's sake, the same bot implemented with WitAI's new Ruby client [wit-ai/wit-ruby](https://github.com/wit-ai/wit-ruby):

``` ruby
actions = {
  say: -> (session_id, context, message) {
    Bot.deliver(
      recipient: {
        id: session_id
      },
      message: {
        text: message
      }
    )
  },
  merge: -> (session_id, context, entities, message) {
    context.merge(entities)
  },
  error: -> (session_id, context, error) {
    puts "ERROR: #{error.message}"
  },
  greet: -> (session_id, context) {
    context.merge(
      greeting: ['Hello', 'Hi', 'Hiya'].sample
    )
  }
}

client = Wit.new(ENV['WIT_ACCESS_TOKEN'], actions)

Bot.on :message do |message|
  client.run_actions message.sender['id'], message.text, {}
end
```

… which is, you know, pretty rough to work with.

What do you think? I'm pretty new to WitAI and I don't know how it changed from when you wrote the gem, so I might have missed some things.

**Comment by benaubin** [comment]
Yeah... that's pretty rough. 

Wit.ai used to send out intents and entities from text, and nothing else (the [wiki for the repl](https://github.com/penne12/wit_bot/wiki/REPL-Output) shows an example response). Now, you have stories which handle most of the stuff for you. 

For the most part, the migration to stories should be pretty easy - wit_bot already has a bot api (though based off of intents). The bot api is actually even designed to handle most of the code you wrote above, like listening to messages and keeping track of threads and users (although it does so in a way that makes it so threads are tracked per conversation). You might have some luck reusing the old [bot api](https://github.com/penne12/wit_bot/wiki/Bot). 

You can then setup a listener for Facebook, like the listener for [MessageBus](https://github.com/penne12/wit_bot/wiki/Integrate-with-Message-Bus). You might send a pr for it, which would be **awesome**. 

Thanks so much!

**Comment by benaubin** [comment]
I've just created a new branch for stories, and removed things related to intents. I'm excited to see your PR - let's continue this on issue #1.

**Comment by rnikunen** [comment]
any further progress on this?
